sudo: required

language: bash

services:
  - docker

before_install:
 - docker pull koalaman/shellcheck:latest

script:
 - docker run -v $(pwd):/scripts --workdir=/scripts koalaman/shellcheck:latest $(grep -lE '^#!/.+(ba)?sh$' $(git ls-files))

matrix:
  fast_finish: true