sudo: required

language: bash

services:
  - docker

before_install:
 - docker pull koalaman/shellcheck:latest

jobs:
  include:
    - stage: test
      script:
      - docker run -v $(pwd):/scripts --workdir=/scripts koalaman/shellcheck:latest $(grep -lE '^#!/.+(ba)?sh$' $(git ls-files))
    -
      script:
      - docker build -t ebooktools/scripts:latest .
      - docker run ebooktools/scripts:latest tests/run.sh
script:

matrix:
  fast_finish: true