language: bash

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

script:
 - shellcheck $(grep -lE '^#!/.+(ba)?sh$' $(git ls-files))

matrix:
  fast_finish: true